apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinyl-api
  namespace: 
spec:
  replicas: 2
  revisionHistoryLimit: 5
  strategy: { type: RollingUpdate }
  selector: { matchLabels: { app: vinyl-api } }
  template:
    metadata: { labels: { app: vinyl-api } }
    spec:
      containers:
        - name: api
          image: 556856552551.dkr.ecr.ap-south-1.amazonaws.com/myvinalcollection:dev-latest
          imagePullPolicy: Always
          ports: [{ containerPort: 8000 }]
          envFrom:
            - configMapRef: { name: vinyl-api-config }
            - secretRef: { name: vinyl-api-secrets }
          startupProbe:
            tcpSocket: { port: 8000 }
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet: { path: /healthz, port: 8000 }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }