apiVersion: v1
kind: Secret
metadata:
  name: mvc-secrets
  namespace: prod
type: Opaque
stringData:
  # NOTE: app expects "MONGO_URI" (per config.py)
  MONGO_URI: "mongodb://appuser:ChangeMeAppPass!@mongo-0.mongo-headless.prod.svc.cluster.local:27017,mongo-1.mongo-headless.prod.svc.cluster.local:27017/appdb?replicaSet=rs0&authSource=appdb"
  # keep these aliases too; harmless
  MONGODB_URI: "mongodb://appuser:ChangeMeAppPass!@mongo-0.mongo-headless.prod.svc.cluster.local:27017,mongo-1.mongo-headless.prod.svc.cluster.local:27017/appdb?replicaSet=rs0&authSource=appdb"
  DB_URI:      "mongodb://appuser:ChangeMeAppPass!@mongo-0.mongo-headless.prod.svc.cluster.local:27017,mongo-1.mongo-headless.prod.svc.cluster.local:27017/appdb?replicaSet=rs0&authSource=appdb"